### ISSUE TITLE
Can't seem to load the model-data.

### ISSUE THREAD

**Issue by newten82** [bitnami/bitnami-docker-tensorflow-inception#2]
**Description**
Can't seem to load the model-data.

tensorflow-serving_1    | 2017-09-07 18:57:23.536781: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable inception found under base path /bitnami/model-data

**Steps to reproduce the issue:**

1. 
```
mkdir /home/jnute/Development/tenserFlow/model-data
curl -o '/home/jnute/Development/tenserFlow/model-data/inception-v3-2016-03-01.tar.gz' 'http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz'
cd /home/jnute/Development/tenserFlow/model-data/
tar xvf inception-v3-2016-03-01.tar.gz 
```

2. Modified /home/jnute/Development/tenserFlow/docker-compose.yml to update model-data path.
```
version: '2'
services:
  tensorflow-serving:
    image: 'bitnami/tensorflow-serving:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - 9000:9000
    volumes:
      - 'tensorflow_serving_data:/bitnami'
      - '/home/jnute/Development/tenserFlow/model-data:/bitnami/model-data'
  tensorflow-inception:
    image: 'bitnami/tensorflow-inception:latest'
    depends_on:
      - tensorflow-serving
    volumes:
      - 'tensorflow_inception_data:/bitnami'
      - '/home/jnute/Development/tenserFlow/model-data:/bitnami/model-data'
volumes:
  tensorflow_serving_data:
    driver: local
  tensorflow_inception_data:
    driver: local
```

3. docker-compose up

**Describe the results you received:**
```
docker-compose up
Recreating tenserflow_tensorflow-serving_1
Recreating tenserflow_tensorflow-inception_1
Attaching to tenserflow_tensorflow-serving_1, tenserflow_tensorflow-inception_1
tensorflow-serving_1    | 
tensorflow-serving_1    | Welcome to the Bitnami tensorflow-serving container
tensorflow-serving_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tensorflow-serving
tensorflow-serving_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tensorflow-serving/issues
tensorflow-serving_1    | Send us your feedback at containers@bitnami.com
tensorflow-serving_1    | 
tensorflow-inception_1  | 
tensorflow-inception_1  | Welcome to the Bitnami tensorflow-inception container
tensorflow-inception_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tensorflow-inception
tensorflow-inception_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tensorflow-inception/issues
tensorflow-inception_1  | Send us your feedback at containers@bitnami.com
tensorflow-inception_1  | 
tensorflow-serving_1    | nami    INFO  Initializing tensorflow-serving
tensorflow-serving_1    | nami    INFO  tensorflow-serving successfully initialized
tensorflow-serving_1    | INFO  ==> Starting tensorflow-serving... 
tensorflow-serving_1    | INFO  ==> Starting ...
tensorflow-serving_1    | TensorFlow Serving is not running... starting server in background mode
tensorflow-inception_1  | nami    INFO  Initializing tensorflow-inception
tensorflow-inception_1  | tensorf INFO  ==> Deleting orphaned links...
tensorflow-inception_1  | nami    INFO  tensorflow-inception successfully initialized
tensorflow-inception_1  | INFO  ==> Starting tensorflow-inception... 
tensorflow-serving_1    | 2017-09-07 19:14:05.850168: I tensorflow_serving/model_servers/server_core.cc:434] Adding/updating models.
tensorflow-serving_1    | 2017-09-07 19:14:05.850238: I tensorflow_serving/model_servers/server_core.cc:485]  (Re-)adding model: inception
tensorflow-serving_1    | 2017-09-07 19:14:05.850367: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable inception found under base path /bitnami/model-data

```

- Output of `docker version`:
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:32:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:32:39 2017
 OS/Arch:      linux/amd64
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
